language: ruby
rvm:
  - 2.5.3

cache: bundler # caching bundler gem packages will speed up build

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site

deploy:
  provider: pages
  local-dir: ./site
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

sudo: false # route your build to the container-based infrastructure for a faster build
