title: Tony DiPasquale
email: hi@tonyd.io
description: >-
  A San Francisco based Photographer and Software Freelancer. Full stack
  developer with JavaScript, Node.js, and iOS & Swift. Outdoor and travel
  photographer.
baseurl: "/"
url: "https://tonyd.io"
twitter: "https://twitter.com/TonyD256"
facebook: "https://www.facebook.com/tonyd256"
instagram: "https://www.instagram.com/tonyd256/"
flickr: "https://www.flickr.com/photos/161286989@N02/"
github: "https://github.com/tonyd256"
linkedin: "https://www.linkedin.com/in/anthonyrdipasquale/"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-compress-images
  - jekyll-analytics

sass:
  style: compressed

permalink: "/blog/:year/:month/:day/:title.html"

pagination:
  enabled: true
  per_page: 10
  sort_reverse: true

compress_images:
  images_path: "images/**/*.{gif,png,jpg,jpeg,svg}"

jekyll-analytics:
  GoogleAnalytics:
    id: UA-80720313-1
    anonymizeIp: false
